# Generated by Django 5.1.4 on 2025-01-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='BookEnddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BookStartdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
