# Generated by Django 5.1.4 on 2025-01-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_bookenddate_student_bookstartdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='BookEnddate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='BookStartdate',
        ),
    ]
