# Generated by Django 5.1.4 on 2025-01-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_demand_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('moderator', 'Moderator')], default='student', max_length=10),
        ),
    ]
