# Generated by Django 5.1.4 on 2025-01-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
    ]
